version: '3.9'
services:
  mysql:
    # environment variables are not a list
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       # root can log in from every host
       MYSQL_ROOT_HOST: '%'
    container_name: mysql
    ports:
      - '3306:3306'
    # For volumes, it will execute files with extensions .sh, .sql and .sql.gz that are found in
    # /docker-entrypoint-initdb.d. Files will be executed in alphabetical order.
    volumes:
      - './schema.sql:/docker-entrypoint-initdb.d/schema.sql/'
    image: 'mysql:8.0'

  hazelcast:
    container_name: hazelcast
    ports:
      - '5701:5701'
    image: 'hazelcast/hazelcast:5.3.0'

# run with
# docker-compose up

# login with
# mysql -uroot -proot